# Generated by Django 4.0.3 on 2022-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0002_alter_face_face_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='face_name',
            field=models.CharField(default=1, help_text='Name', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='face',
            name='face_id',
            field=models.IntegerField(help_text='Code'),
        ),
    ]
