# Generated by Django 4.0.3 on 2022-03-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0004_alter_face_face_id_alter_face_face_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='face_id',
            field=models.CharField(help_text='Code', max_length=30, verbose_name='idFace'),
        ),
    ]
