# Generated by Django 4.0.3 on 2022-03-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0005_alter_face_face_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='face_id',
            field=models.CharField(help_text='Code', max_length=6, verbose_name='idFace'),
        ),
        migrations.AddConstraint(
            model_name='face',
            constraint=models.CheckConstraint(check=models.Q(('face_id__length__gte', 6)), name='upload_app_face_title_length'),
        ),
    ]
