# Generated by Django 4.0.3 on 2022-03-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0006_alter_face_face_id_face_upload_app_face_title_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='face',
            name='upload_app_face_title_length',
        ),
        migrations.RemoveField(
            model_name='face',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='face',
            name='face_name',
        ),
        migrations.AddField(
            model_name='face',
            name='face_group_ch',
            field=models.CharField(default=None, help_text='Организация', max_length=50, verbose_name='face_group'),
        ),
        migrations.AddField(
            model_name='face',
            name='face_id_ch',
            field=models.CharField(default=None, help_text='Code', max_length=6, unique=True, verbose_name='idFace'),
        ),
        migrations.AddField(
            model_name='face',
            name='face_name_ch',
            field=models.CharField(default=None, help_text='Name', max_length=30, verbose_name='faceName'),
        ),
        migrations.AddField(
            model_name='face',
            name='face_token_int',
            field=models.IntegerField(default=None, help_text='Токен', unique=True, verbose_name='faceToken'),
        ),
        migrations.AddField(
            model_name='face',
            name='face_token_valid_bol',
            field=models.BooleanField(default=None, help_text='Токен действующий?', verbose_name='face_valid'),
        ),
        migrations.AddField(
            model_name='face',
            name='face_worker_bol',
            field=models.BooleanField(default=None, help_text='Постоянный работник?', verbose_name='face_worker'),
        ),
        migrations.AlterField(
            model_name='face',
            name='face_img',
            field=models.ImageField(help_text='Загрузите фото', unique=True, upload_to='images/', verbose_name='faceImg'),
        )
    ]
