# Generated by Django 4.0.3 on 2022-03-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0007_remove_face_upload_app_face_title_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='face_token_int',
        ),
        migrations.AddField(
            model_name='face',
            name='face_token_ch',
            field=models.CharField(default=None, help_text='Токен', max_length=6, verbose_name='faceToken'),
        ),
        migrations.AlterField(
            model_name='face',
            name='face_id_ch',
            field=models.CharField(default=None, help_text='Code', max_length=6, verbose_name='idFace'),
        ),
        migrations.AlterField(
            model_name='face',
            name='face_img',
            field=models.ImageField(help_text='Загрузите фото', upload_to='images/', verbose_name='faceImg'),
        ),
    ]
